package info.tregmine.death;

import java.util.Random;

public class Insult {

	public static String random() {
		String[] dieText = new String[174];
		dieText[0] = "Better luck next time.";
		dieText[1] = "Did you just really do that?";
		dieText[2] = "And you will never see heaven.";
		dieText[3] = "You just lost all your stuff.";
		dieText[4] = "MESSAGE REMOVE";
		dieText[5] = "MESSAGE REMOVE";
		dieText[6] = "Damnit again?";
		dieText[7] = "Why did you jump?";
		dieText[8] = "MESSAGE REMOVE";
		dieText[9] = "Never drive drunk.";
		dieText[10] = "and lost some cash.";
		dieText[11] = "and never saw the light.";
		dieText[12] = "Can someone clean that mess up?";
		dieText[13] = "Damnit not another one.";
		dieText[14] = "We have the power to revive you.";
		dieText[16] = "You just won the Darwin Award.";
		dieText[17] = "MESSAGE REMOVE";
		dieText[18] = "Next time you get banned!";
		dieText[19] = "MESSAGE REMOVE";
		dieText[20] = "MESSAGE REMOVE";
		dieText[21] = "He death man!";
		dieText[22] = "He always finds himself lost in thought - it's an unfamiliar territory";
		dieText[23] = "He doesn't know the meaning of the word \"fear\" - but then again he doesn't know the meaning of most words";
		dieText[24] = "MESSAGE REMOVE";
		dieText[25] = "Oh my God, look at you. Anyone else hurt in the accident?";
		dieText[26] = "MESSAGE REMOVE";
		dieText[27] = "MESSAGE REMOVE";
		dieText[28] = "I've seen people like you before, but I had to pay admission!";
		dieText[29] = "He was happily married - but his wife wasn't, until now.";
		dieText[30] = "I heard that you went to the haunted house and they offered you a job.";
		dieText[31] = "Can someone get that necrophilia of that corps.";
		dieText[32] = "I bet your brain feels as good as new, seeing that you've never used it.";
		dieText[33] = "If we were to kill everybody who hates you, it wouldn't be murder; it would be genocide!";
		dieText[34] = "I don't think you are a fool. But then, what's my own humble opinion against thousands of others?";
		dieText[35] = "Nobody says that you are dumb. They just say you were sixteen years old before you learned how to wave goodbye.";
		dieText[36] = "Ordinarily people live and learn. You just died.";
		dieText[37] = "NOOOO I forgot to ask you if I could get your stuff, euhmm il take it anyway.";
		dieText[38] = "Ooohhh did I just release all those mobs on you?";
		dieText[39] = "I don't hold your behavior against you because I realize it was caused by childhood trauma.";
		dieText[40] = "How was your date with death.";
		dieText[41] = "How was your date with the Grim Reper";
		dieText[42] = "Ohh it was you, I thought it was a zombie I killed";
		dieText[43] = "Any similarity between you and a human is purely coincidental!";
		dieText[44] = "Anyone who told you to be yourself couldn't have given you worse advice.";
		dieText[45] = "Calling you stupid would be an insult to stupid people.";
		dieText[46] = "Do you ever wonder what life would be like if you'd had enough oxygen at birth?";
		dieText[47] = "Don't you have a terribly empty feeling - in your skull?";
		dieText[48] = "Do you still love nature, despite what it did to you?";
		dieText[49] = "Pardon me, but you've obviously mistaken me for someone who gives a damn.";
		dieText[50] = "No 72 virgins for you.";
		dieText[51] = "If ignorance is bliss, you must be the happiest person alive.";
		dieText[52] = "Why can't you just fucking die";
		dieText[53] = "Nice to meeting you again - welcome back";
		dieText[54] = "If you were any more stupid, You'd have to be watered twice a week.";
		dieText[55] = "He died of SHC - Spontaneous human combustion";
		dieText[56] = "MESSAGE REMOVE";
		dieText[57] = "Can someone go to Walmart and get a funeral casket";
		dieText[58] = "Strange no one ate your funeral, are you to stupid to have friends?";
		dieText[59] = "MESSAGE REMOVE";
		dieText[60] = "MESSAGE REMOVE";
		dieText[61] = "it was the Obama administration that got him killed";
		dieText[62] = "MESSAGE REMOVE";
		dieText[63] = "MESSAGE REMOVE";
		dieText[64] = "GAME OVER - PRESS SELECT TO CONTINUE";
		dieText[65] = "What did a cat do that to you";
		dieText[66] = "Wait, why arent you dead?";
		dieText[67] = "I think the grim reper loves you as do continue to die all the time";
		dieText[67] = "MESSAGE REMOVE";
		dieText[68] = "Either  he's dead or my watch has stopped.";
		dieText[69] = "Luckily you had those extra live's";
		dieText[70] = "Stop dying or you will be the only one this month in death's collecbook";
		dieText[71] = "MESSAGE REMOVE";
		dieText[72] =  "Stop dying you are harasing death";
		dieText[73] =  "MESSAGE REMOVE";
		dieText[74] = "MESSAGE REMOVE";
		dieText[75] = "He is braindead - ooh no wait its unused";
		dieText[76] = "Blame it on einand";
		dieText[77] = "Was it Tix92 that did kill you this time?";
		dieText[78] = "Did you have to build that high, and fall down?"; 
		dieText[79] = "There are three natural anaesthetics: Sleep, fainting, and death."; 
		dieText[80] = "Didn't you see that creeper crawling up on you from behind?";
		dieText[81] = "Did you order a hit man for suicide?";
		dieText[82] = "is dead, call 991";
		dieText[83] = "It was a Hit And Run";
		dieText[84] = "That why you never shall play with water";
		dieText[85] = "You are such a loser, you can't even die normal";
		dieText[86] = "That was a trap, or you are just plain stupid";
		dieText[87] = "I shall revenge your living";
		dieText[88] = "I know what you did last summer";
		dieText[89] = "Spider wont make you spider man, as they are not radioactive";
		dieText[90] = "Scream!";
		dieText[91] = "Wow still alive? oh wait, Scream 4";
		dieText[92] = "MESSAGE REMOVE";
		dieText[93] = "Fucking a skeleton is considered necrophilia and is thus punishable by death.";
		dieText[94] = "You died that fast that I didn't even notice it";
		dieText[95] = "Nice finally I found some Blood Stone";
		dieText[96] = "Strange can you die doing that?";
		dieText[97] = "You must be an inventor since you invent so many ways to die";
		dieText[98] = "Leave the poor mob alone";
		dieText[99] = "Why cant you just stay dead?";
		dieText[100] = "You died so many times so we have to rename the word die to your name";
		dieText[101] = "Did you see Elvis?";
		dieText[102] = "Mess with the best and die like the rest.";
		dieText[103] = "MESSAGE REMOVE";
		dieText[104] = "Camrenn still loves you!";
		dieText[105] = "Camrenn forced her love on you, thats why you died";
		dieText[106] = "Sorry it was our princess Camrenn who wish to have you killed";
		dieText[107] = "That was a suprice attack by Camrenn";
		dieText[108] = "Please understand Camrenn don't want to marry you";
		dieText[108] = "Oh what's that? your dead? 'what a shame'";
		dieText[108] = "That creeper just wanted a hug!";
		dieText[108] = "Is it day time yet?";
			dieText[109] = "Oops, you did it again!";
			dieText[110] = "Yes, arrows kill";
			dieText[111] = "Death before dishonor!";
			dieText[112] = "Live free or die!";
			dieText[113] = "no, you can't swim in lava";
			dieText[114] = "And again you think... \"I shall heal my self\"... and again you die.";
			dieText[115] = "where is a pig when you need one...";
			dieText[116] = "You've got death!";
			dieText[117] = "It is dark, your exits were north, east, and west, you were eaten by a grue";
			dieText[118] = "MESSAGE REMOVE";
			dieText[119] = "Warning: 3 Lives Remaining!";
			dieText[120] = "Walk towards the light! No! The other light!";
			dieText[121] = "What do you think you'd accomplish by doing that?";
			dieText[122] = "The secret of flying? No, it's not throwing yourself at the ground thinking you will miss...";
			dieText[123] = "Know what the last thing was that went through your head? Your ass!";
			dieText[124] = "Applying for work at the suicide hotline never required suicide attempts!";
			dieText[125] = "You found your first wild wolf huh? Next time, bring bones.";
			dieText[126] = "One of those creepers exploded again huh? Yeah, they creep me out too...";
			dieText[127] = "Monsters aren't as nice as they look!";
			dieText[128] = "Don't try to catch those things flying at you.";
			dieText[129] = "You just proved dying is easy";
			dieText[130] = "BANG! Creeper shot";
			dieText[131] = "Hello? Yes, this is death calling; I'd like a refund, this body has no brain";
			dieText[132] = "Unlike in the movies, pig crashes don't let you walk away unharmed";
			dieText[133] = "Whos bright idea was it to poke that creeper?";
			dieText[134] = "BOOM goes the creeper!";
			dieText[135] = "You're alive! Syke.";
			dieText[136] = "The giant green exploding creeper found you once, he can do it again (and again).";
			dieText[137] = "Was it Blackx's fill tool that killed you (and the server) this time?.";
			dieText[138] = "Angry Wolf was not appeased.";
			dieText[139] = "Never gonna give you up, never gonna let you down... Looks like Rick let you down";
			dieText[140] = "REMOVED";
			dieText[141] = "REMOVED";
			dieText[142] = "TNT doesn't work on this server yet you seem to have killed yourself with it";
			dieText[143] = "Only an oaf like you could have bungled that up";
			dieText[144] = "REMOVED";
			dieText[145] = "Quick, take his stuff!";
			dieText[146] = "REMOVED";
			dieText[147] = "Maybe you shouldn't be using a gold sword...";
			dieText[148] = "That is why you should carry arrows when you use a bow";
			dieText[149] = "Looks like you got alittle *puts on glasses* creeped out";
			dieText[150] = "wait going going gone yup hes dead!!";
			dieText[151] = "I know you Had an itch,but couldn't you wait until u were in private?";
			dieText[152] = "Feel Admins's wrath";
			dieText[153] = "JAYT8 welcome you to the server by doing this.";
			dieText[154] = "Even the nether rejects you";
			dieText[155] = "You were smoth by the hammer of Thor";
			dieText[156] = "was smited by Josh121297 from senior heaven";

			dieText[157] = "You did see that ledge there...didn't you?";
			dieText[158] = "Another one assassinated by Toddtedd.";
			dieText[159] = "Another one bites the dust.";
			
			dieText[160] = "You dun goofed.";
			dieText[161] = "You weren't very lucky, punk.";
			dieText[162] = "HEADSHOT!";
			dieText[163] = "Pow! Right in the kisser!";
			dieText[164] = "Does that mean that the mushroom WAS Poisonous?";
			dieText[165] = "Well, there's your problem. You're dead!";
			dieText[166] = "Note to self: Do not dry hump TNT";
			dieText[167] = "Molesting creepers is a no-no.";
			dieText[168] = "Please keep your arms and legs inside the coffin at all times.";
			dieText[169] = "Bloody bugger to you, you beastly bastard.";

			dieText[170] = "You had one job...";
			dieText[171] = "You talked about Fight Club didn't you.";
			dieText[172] = "You got the ol' Onesey Twosey";
			dieText[173] = "Pow! Right in the kisser!";
			
			/*
			dieText[174] = "You've been hit by! You've been struct by! Lightning. Smooth.";
			dieText[175] = "what do you want me to say something funny?";
			dieText[176] = "Was a Templar, and was dealt with";
			dieText[177] = "tried to catch an anvil.";
			dieText[178] = "was accidentally killed by OgreTusk!";
			dieText[179] = "made BlackX angry";
			
			dieText[180] = "tried playing catch with a ghast.";
			dieText[181] = "i think einand tricked me.";
			dieText[182] = "gangnamed too hard!";
			dieText[183] = "didn't survive the reichenbac fall.";
			dieText[184] = "Never taste a drink from strangers again";
			dieText[185] = "became a human torch";
			dieText[186] = "Did you like that, when the zombie sheep tasted your brain";
			dieText[187] = "appearantly played spleef against LilKiw";
			dieText[188] = "Next time call the Ghastbusters";
			dieText[189] = "Bloody bugger to you, you beastly bastard.";
			

			*/
			
	    Random ran = new Random( System.currentTimeMillis() );
	    int  rand = ran.nextInt(dieText.length);
		return dieText[rand];
	}
	
	
}
