package info.tregmine.api;

import java.util.Random;

public class Insult
{
    public static String random()
    {
        String[] dieText =
                new String[] {
                        "Better luck next time.",
                        "Did you just really do that?",
                        "And you will never see heaven.",
                        "You just lost all your stuff.",
                        "Damnit again?",
                        "Why did you jump?",
                        "Never drive drunk.",
                        "and lost some cash.",
                        "and never saw the light.",
                        "Can someone clean that mess up?",
                        "Damnit not another one.",
                        "We have the power to revive you.",
                        "You just won the Darwin Award.",
                        "Next time you get banned!",
                        "He death man!",
                        "He always finds himself lost in thought - it's an unfamiliar territory",
                        "He doesn't know the meaning of the word \"fear\" - but then again he doesn't know the meaning of most words",
                        "Oh my God, look at you. Anyone else hurt in the accident?",
                        "I've seen people like you before, but I had to pay admission!",
                        "He was happily married - but his wife wasn't, until now.",
                        "I heard that you went to the haunted house and they offered you a job.",
                        "Can someone get that necrophilia of that corps.",
                        "I bet your brain feels as good as new, seeing that you've never used it.",
                        "If we were to kill everybody who hates you, it wouldn't be murder, it would be genocide!",
                        "I don't think you are a fool. But then, what's my own humble opinion against thousands of others?",
                        "Nobody says that you are dumb. They just say you were sixteen years old before you learned how to wave goodbye.",
                        "Ordinarily people live and learn. You just died.",
                        "NOOOO I forgot to ask you if I could get your stuff, euhmm il take it anyway.",
                        "Ooohhh did I just release all those mobs on you?",
                        "I don't hold your behavior against you because I realize it was caused by childhood trauma.",
                        "How was your date with death.",
                        "How was your date with the Grim Reper",
                        "Ohh it was you, I thought it was a zombie I killed",
                        "Any similarity between you and a human is purely coincidental!",
                        "Anyone who told you to be yourself couldn't have given you worse advice.",
                        "Calling you stupid would be an insult to stupid people.",
                        "Do you ever wonder what life would be like if you'd had enough oxygen at birth?",
                        "Don't you have a terribly empty feeling - in your skull?",
                        "Do you still love nature, despite what it did to you?",
                        "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
                        "No 72 virgins for you.",
                        "If ignorance is bliss, you must be the happiest person alive.",
                        "Why can't you just fucking die",
                        "Nice to meeting you again - welcome back",
                        "If you were any more stupid, You'd have to be watered twice a week.",
                        "He died of SHC - Spontaneous human combustion",
                        "Can someone go to Walmart and get a funeral casket",
                        "Strange no one ate your funeral, are you to stupid to have friends?",
                        "it was the Obama administration that got him killed",
                        "GAME OVER - PRESS SELECT TO CONTINUE",
                        "What did a cat do that to you",
                        "Wait, why arent you dead?",
                        "I think the grim reper loves you as do continue to die all the time",
                        "Either  he's dead or my watch has stopped.",
                        "Luckily you had those extra live's",
                        "Stop dying or you will be the only one this month in death's collecbook",
                        "Stop dying you are harasing death",
                        "He is braindead - ooh no wait its unused",
                        "Did you have to build that high, and fall down?",
                        "There are three natural anaesthetics: Sleep, fainting, and death.",
                        "Didn't you see that creeper crawling up on you from behind?",
                        "Did you order a hit man for suicide?",
                        "is dead, call 991",
                        "It was a Hit And Run",
                        "That why you never shall play with water",
                        "You are such a loser, you can't even die normal",
                        "That was a trap, or you are just plain stupid",
                        "I shall revenge your living",
                        "I know what you did last summer",
                        "Spider wont make you spider man, as they are not radioactive",
                        "Scream!",
                        "Wow still alive? oh wait, Scream 4",
                        "Fucking a skeleton is considered necrophilia and is thus punishable by death.",
                        "You died that fast that I didn't even notice it",
                        "Nice finally I found some Blood Stone",
                        "Strange can you die doing that?",
                        "You must be an inventor since you invent so many ways to die",
                        "Leave the poor mob alone",
                        "Why cant you just stay dead?",
                        "You died so many times so we have to rename the word die to your name",
                        "Did you see Elvis?",
                        "Mess with the best and die like the rest.",
                        "Camrenn still loves you!",
                        "Camrenn forced her love on you, thats why you died",
                        "Sorry it was our princess Camrenn who wish to have you killed",
                        "That was a suprice attack by Camrenn",
                        "Please understand Camrenn don't want to marry you",
                        "Oh what's that? your dead? 'what a shame'",
                        "That creeper just wanted a hug!",
                        "Is it day time yet?",
                        "Oops, you did it again!",
                        "Yes, arrows kill",
                        "Death before dishonor!",
                        "Live free or die!",
                        "no, you can't swim in lava",
                        "And again you think... \"I shall heal my self\"... and again you die.",
                        "where is a pig when you need one...",
                        "You've got death!",
                        "It is dark, your exits were north, east, and west, you were eaten by a grue",
                        "Warning: 3 Lives Remaining!",
                        "Walk towards the light! No! The other light!",
                        "What do you think you'd accomplish by doing that?",
                        "The secret of flying? No, it's not throwing yourself at the ground thinking you will miss...",
                        "Know what the last thing was that went through your head? Your ass!",
                        "Applying for work at the suicide hotline never required suicide attempts!",
                        "You found your first wild wolf huh? Next time, bring bones.",
                        "One of those creepers exploded again huh? Yeah, they creep me out too...",
                        "Monsters aren't as nice as they look!",
                        "Don't try to catch those things flying at you.",
                        "You just proved dying is easy",
                        "BANG! Creeper shot",
                        "Hello? Yes, this is death calling, I'd like a refund, this body has no brain",
                        "Unlike in the movies, pig crashes don't let you walk away unharmed",
                        "Whos bright idea was it to poke that creeper?",
                        "BOOM goes the creeper!",
                        "You're alive! Syke.",
                        "The giant green exploding creeper found you once, he can do it again (and again).",
                        "Was it Blackx's fill tool that killed you (and the server) this time?.",
                        "Angry Wolf was not appeased.",
                        "Never gonna give you up, never gonna let you down... Looks like Rick let you down",
                        "REMOVED",
                        "REMOVED",
                        "TNT doesn't work on this server yet you seem to have killed yourself with it",
                        "Only an oaf like you could have bungled that up",
                        "REMOVED",
                        "Quick, take his stuff!",
                        "REMOVED",
                        "Maybe you shouldn't be using a gold sword...",
                        "That is why you should carry arrows when you use a bow",
                        "Looks like you got alittle *puts on glasses* creeped out",
                        "wait going going gone yup hes dead!!",
                        "I know you Had an itch,but couldn't you wait until u were in private?",
                        "Feel Admins's wrath",
                        "JAYT8 welcome you to the server by doing this.",
                        "Even the nether rejects you",
                        "You were smoth by the hammer of Thor",
                        "was smited by Josh121297 from senior heaven",

                        "You did see that ledge there...didn't you?",
                        "Another one assassinated by Toddtedd.",
                        "Another one bites the dust.",

                        "You dun goofed.",
                        "You weren't very lucky, punk.",
                        "HEADSHOT!",
                        "Pow! Right in the kisser!",
                        "Does that mean that the mushroom WAS Poisonous?",
                        "Well, there's your problem. You're dead!",
                        "Note to self: Do not dry hump TNT",
                        "Molesting creepers is a no-no.",
                        "Please keep your arms and legs inside the coffin at all times.",
                        "Bloody bugger to you, you beastly bastard.",

                        "You had one job...",
                        "You talked about Fight Club didn't you.",
                        "You got the ol' Onesey Twosey",
                        "Pow! Right in the kisser!",

                // "You've been hit by! You've been struct by! Lightning. Smooth.",
                // "what do you want me to say something funny?",
                // "Was a Templar, and was dealt with",
                // "tried to catch an anvil.",
                // "was accidentally killed by OgreTusk!",
                // "made BlackX angry",

                // "tried playing catch with a ghast.",
                // "gangnamed too hard!",
                // "didn't survive the reichenbac fall.",
                // "Never taste a drink from strangers again",
                // "became a human torch",
                // "Did you like that, when the zombie sheep tasted your brain",
                // "appearantly played spleef against LilKiw",
                // "Next time call the Ghastbusters",
                // "Bloody bugger to you, you beastly bastard.",
                };

        Random ran = new Random(System.currentTimeMillis());
        int rand = ran.nextInt(dieText.length);
        return dieText[rand];
    }
}
