name: tregmine
main: info.tregmine.Tregmine
version: 2.0.0
website: http://tregmine.info
author: Ein Andersson, Emil Hernvall, Josh Morgan, James Sherlock, Rob Catron, Joe Notaro
description: Tregmine
loadbefore: [BlockLog,GameMagic]

commands:
  admins:
    description: Send a message to all active admins
    usage: /admins message
    aliases: a
  alert:
    description: Change your alerts (Cyan text in chat)
    usage: /alert
  allclear:
    description: Check if any blocks have been changed
    usage: /allclear [radius]
  guardians:
    description: Send a message to all active guardians
    usage: /guardians message
    aliases: g
  coders:
    description: Send a message to all online coders
    usage: /coders message
    aliases: c
  creative:
    description: Switch to creative mode (admins and builders only)
    usage: /creative
  survival:
    description: Switch to survival mode (admins and builders only)
    usage: /survival
  action:
    description: Indicates an action in chat
    usage: /action message
    aliases: me
  ban:
    description: Ban the specified player
    usage: /ban player
  badge:
    description: All commands for badges
    usage: /badge
  bless:
    description: Specify the player for which the next block will be blessed
    usage: /bless player
  blockhere:
    description: Create a block of dirt beneath your feet (admins and builders only)
    usage: /blockhere
  brush:
    description: Create a brush
    usage: /brush <material> <radius>
  cname:
    description: Change your name and color (admin only)
    usage: /cname color new_name
  channel:
    description: Change to the specified channel
    usage: /channel channel_name
  channelview:
    description: View all channels whilst in one channel (admins)
    usage: /channelview <on/off>
  clean:
    description: Clean your inventory
    usage: /clean
  createmob:
    description: Create mobs from empty air (admin only)
    usage: /createmob mob_type amount [name]
  createwarp:
    description: Create a warp at your present location (admin only)
    usage: /createwarp warp_name
  fill:
    description: Fill, replace and copy blocks using a wooden spade (admins and builders only)
    usage: /fill
  fly:
    description: Fly, Toggles flying using the Player Flags system
    usage: /fly
  force:
    description: Force someone into a channel
    usage: /force player channel
  forceblock:
    description: Stop people forcing you into channels
    usage: /forceblock <on/off/status>
  give:
    description: Give a user an item (admin only)
    usage: /give player item amount data
  home:
    description: Teleport to, or set, your home
    usage: /home
  ignore:
    description: Ignore a player (not staff)
    usage: /ignore <add/remove> <player_name> or /ignore <list>
  inv:
    description: Look in a players inventory (admin only)
    usage: /inv <player>
  invlog:
    description: Toggle inventory logging display
    usage: /invlog <on/off/status>
  item:
    description: Spawn an item
    usage: /item item amount data (admin only)
  keyword:
    description: Set your keyword
    usage: /keyword keyword
  kick:
    description: Kick a player (admins and guardians only)
    usage: /unkown
  lot:
    description: Manage your lot
    usage: /lot
  mentor:
    description: Make yourself available for mentoring (residents and above)
    usage: /mentor queue|complete|cancel
  msg:
    description: Message another player
    usage: /msg player message
    aliases: [m, tell]
  newspawn:
    description: Temporarily change the spawn on this map (admin only)
    usage: /newspawn
  normal:
    description: Become a normal player until you sign back on (admins, guardians and builders only)
    usage: /normal
  nuke:
    description: Kill all mobs on this map (admins and guardians only)
    usage: /nuke
  password:
    description: Set your password
    usage: /password password
  pos:
    description: Prints your position to the console
    usage: /pos
  quitmessage:
    description: Set a quit message (donators only)
    usage: /quitmessage <message>
  regeneratechunk:
    description: Regenerate the current chunk (admin only)
    usage: /regeneratechunk
  remitems:
    description: remove all items in the specified radius
    usage: /remitems radius
  repair:
    description: Repair special tools
    usage: /repair
  report:
    description: Adds a report to the players record
    usage: /report player message
  say:
    description: Speak as god (admins only)
    usage: /say message
  seen:
    description: Check a players last login
    usage: /seen player
  sell:
    description: Sell stuff to the central bank
    usage: /sell
  sendto:
    description: Send a player to another world (admins only)
    usage: /sendto player world
  setbiome:
    description: Set the selected area's biome
    usage: /setbiome biome 
  setspawner:
    description: Change a mob spawners type (admins only)
    usage: /setspawner
  spawn:
    description: Go back to spawn
    usage: /spawn
  summon:
    description: Summon a player to your location
    usage: /summon player
    aliases: s
  support:
    description: Send support message
    usage: /support message
    aliases: sup
  testfill:
    description: Like fill, but with fake blocks (admins and builders only)
    usage: /testfill
  tool:
    description: Spawn in Special Tools (Admin)
    usage: /tool
  town:
    description: Shorthand for /zone
    usage: /town delete \
           /town adduser <player> <perm> \
           /town deluser <player> \
           /town entermsg <message> \
           /town exitmsg <message> \
           /town pvp <true/false> \
           /town hostiles <true/false> \
           /town enter <true/false> \
           /town place <true/false> \
           /town destroy <true/false> \
           /town info [perm]
  tp:
    description: Teleport to a player
    usage: /tp player
  tpshield:
    description: Prevent players from teleporting to you (donators only)
    usage: /tpshield
    aliases: tpblock
  tpto:
    description: Teleport to specified coordinates (admin only)
    usage: /tpto x y z
  time:
    description: Change the time of day (donators only)
    usage: /time day|night|normal
  trade:
    description: Trade safely
    usage: /trade player
  update:
    description: See what was last updated!
    usage: /update [version number]
  vanish:
    description: Become invisible (admin only)
    usage: /vanish <on|off>
  wallet:
    description: Modify your wallet
    usage: /wallet
  warn:
    description: Warn a user (guardian and admin only)
    usage: /warn <hard|soft> <player> <message>
  warp:
    description: Warp to a specified city
    usage: /warp city
  weather:
    description: Change weather (donators only)
    usage: /weather <downfall or clear>
  who:
    description: Look up information about a player
    usage: /who <player>
  zone:
    description: Modify a zone
    usage: /zone create <name> <owner> \
           /zone delete <name> \
           /zone adduser <name> <player> <perm> \
           /zone deluser <name> <player> \
           /zone entermsg <zone> <message> \
           /zone exitmsg <zone> <message> \
           /zone pvp <zone> <true/false> \
           /zone hostiles <zone> <true/false> \
           /zone enter <zone> <true/false> \
           /zone place <zone> <true/false> \
           /zone destroy <zone> <true/false> \
           /zone info <name> [perm]
  lottery:
    description: Type /lottery for additional info.
    usage: /lottery
  head:
    description: Receive a specified player's head.
    usage: /head <player>
  hide:
    description: Hide logon message
    usage: /hide
  watchchunks:
    description: Informs the player when they load new and old chunks without spam
    usage: /watchchunks on/off/status
  webkick:
    description: Kick <player> from web chat for 10 minutes
    usage: /webkick <player> <message>
  chunkcount:
    description: See number of chunks in each world
    usage: /chunkcount
