
package info.tregmine.christmas.populators;

import java.util.Random;
import org.bukkit.Chunk;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.generator.BlockPopulator;

public class SkySignPopulator extends BlockPopulator {

	private static final int SIGN_SPAWN_CHANCE = 1; // Out of 1000

	public void populate(World world, Random random, Chunk source) {
		if (random.nextInt(1000) <= SIGN_SPAWN_CHANCE) {
			int x = (source.getX() << 4) + random.nextInt(16);
			int z = (source.getZ() << 4) + random.nextInt(16);
			int y = world.getHighestBlockYAt(x, z);
			generate(world, random, x - 1 , y + 50, z - 1);
		}
	}

	@SuppressWarnings("deprecation")
	public boolean generate(World world, Random rand, int i, int j, int k) {
		
		world.getBlockAt(i + 0, j + 0, k + 3).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 4).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 5).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 7).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 8).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 9).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 10).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 11).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 12).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 13).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 14).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 15).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 16).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 17).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 18).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 19).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 20).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 21).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 22).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 23).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 24).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 25).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 26).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 27).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 28).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 29).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 30).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 31).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 32).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 33).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 34).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 35).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 36).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 37).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 38).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 39).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 40).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 41).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 42).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 43).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 44).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 45).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 46).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 47).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 48).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 49).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 0, k + 50).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 1, k + 51).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 2, k + 1).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 2, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 19).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 23).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 24).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 27).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 28).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 30).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 31).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 32).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 33).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 34).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 41).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 2, k + 52).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 3, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 3, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 19).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 23).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 24).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 27).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 28).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 30).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 31).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 32).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 33).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 34).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 41).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 3, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 4, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 4, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 4, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 5, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 5, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 5, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 6, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 6, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 11).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 12).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 47).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 48).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 6, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 7, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 7, k + 3).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 6).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 11).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 12).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 47).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 48).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 7, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 8, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 8, k + 2).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 3).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 4).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 5).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 6).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 7).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 8, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 9, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 9, k + 2).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 3).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 4).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 9, k + 5).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 9, k + 6).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 7).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 16).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 9, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 10, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 10, k + 2).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 3).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 6).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 7).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 9).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 11).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 12).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 14).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 17).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 19).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 23).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 24).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 27).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 28).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 41).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 10, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 11, k + 0).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 11, k + 2).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 3).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 6).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 7).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 10).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 11).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 12).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 13).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 18).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 19).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 20).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 21).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 23).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 24).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 25).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 26).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 27).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 28).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 41).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 45).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 46).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 11, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 12, k + 2).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 12, k + 3).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 12, k + 52).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 8).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 9).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 10).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 11).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 12).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 13).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 14).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 15).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 16).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 17).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 18).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 19).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 20).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 21).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 22).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 23).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 24).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 25).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 26).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 27).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 28).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 29).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 30).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 31).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 32).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 33).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 34).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 35).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 36).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 37).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 38).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 39).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 40).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 41).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 42).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 43).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 44).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 45).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 46).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 47).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 48).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 49).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 50).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 51).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 54).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 55).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 56).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 57).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 58).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 59).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 60).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 61).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 62).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 63).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 64).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 13, k + 65).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 14, k + 7).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 14, k + 66).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 15, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 15, k + 9).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 18).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 19).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 23).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 24).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 27).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 28).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 37).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 38).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 41).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 42).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 46).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 47).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 48).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 62).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 15, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 16, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 16, k + 9).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 18).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 19).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 23).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 24).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 27).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 28).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 30).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 35).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 37).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 38).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 41).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 42).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 46).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 47).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 48).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 52).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 62).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 16, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 17, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 17, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 30).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 17, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 18, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 18, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 30).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 18, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 19, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 19, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 19, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 20, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 20, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 20, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 21, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 21, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 35).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 21, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 22, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 22, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 35).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 48).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 59).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 22, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 23, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 23, k + 9).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 23).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 24).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 27).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 28).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 30).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 35).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 37).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 38).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 41).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 42).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 44).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 46).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 47).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 48).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 50).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 52).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 57).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 60).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 62).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 23, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 24, k + 6).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 24, k + 9).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 10).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 11).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 12).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 13).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 14).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 16).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 17).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 20).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 21).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 23).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 24).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 25).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 26).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 27).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 28).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 31).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 32).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 33).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 34).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 37).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 38).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 39).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 40).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 41).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 42).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 45).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 46).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 47).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 48).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 49).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 53).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 54).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 55).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 56).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 61).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 62).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 63).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 64).setTypeIdAndData(35, (byte) 13, true);
		world.getBlockAt(i + 0, j + 24, k + 67).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 25, k + 6).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 25, k + 7).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 25, k + 66).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 7).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 26, k + 8).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 9).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 10).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 11).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 12).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 13).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 14).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 15).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 16).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 17).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 18).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 19).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 20).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 21).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 22).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 23).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 24).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 25).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 26).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 29).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 30).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 31).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 32).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 33).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 34).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 35).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 36).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 37).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 38).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 39).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 40).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 41).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 42).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 43).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 44).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 45).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 46).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 47).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 48).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 49).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 50).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 51).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 52).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 53).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 54).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 55).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 56).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 57).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 58).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 59).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 60).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 61).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 62).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 63).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 64).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 26, k + 65).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 27, k + 8).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 9).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 10).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 11).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 12).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 13).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 14).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 15).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 16).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 17).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 18).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 19).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 20).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 21).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 22).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 23).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 24).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 25).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 26).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 28).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 27, k + 29).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 33).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 37).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 41).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 45).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 46).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 47).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 51).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 52).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 53).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 57).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 61).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 27, k + 65).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 28, k + 27).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 28, k + 31).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 34).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 43).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 48).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 54).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 55).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 56).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 59).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 62).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 64).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 66).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 28, k + 68).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 27).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 29, k + 31).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 43).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 29, k + 44).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 48).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 56).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 58).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 59).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 29, k + 60).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 62).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 63).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 64).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 66).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 29, k + 68).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 27).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 30, k + 30).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 31).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 30, k + 32).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 34).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 44).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 48).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 50).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 55).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 56).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 58).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 60).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 62).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 64).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 66).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 67).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 30, k + 68).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 27).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 28).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 0, j + 31, k + 30).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 32).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 34).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 35).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 36).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 38).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 39).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 40).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 42).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 44).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 48).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 49).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 50).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 54).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 55).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 56).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 58).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 60).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 62).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 63).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 64).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 66).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 31, k + 67).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 31, k + 68).setTypeIdAndData(35, (byte) 14, true);
		world.getBlockAt(i + 0, j + 32, k + 28).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 30).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 32).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 34).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 36).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 38).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 39).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 40).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 42).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 44).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 49).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 54).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 55).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 56).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 58).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 60).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 63).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 66).setType(Material.SNOW_BLOCK);
		world.getBlockAt(i + 0, j + 32, k + 68).setType(Material.SNOW_BLOCK);
		return true;
	}
}
