
package info.tregmine.christmas.populators;

import java.util.Random;
import org.bukkit.Chunk;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.generator.BlockPopulator;

public class WreathPopulator extends BlockPopulator {

	private static final int WREATH_SPAWN_CHANCE = 1; // Out of 1000

	public void populate(World world, Random random, Chunk source) {
		if (random.nextInt(1000) <= WREATH_SPAWN_CHANCE) {
			int x = (source.getX() << 4) + random.nextInt(16);
			int z = (source.getZ() << 4) + random.nextInt(16);
			int y = world.getHighestBlockYAt(x, z);
			generate(world, random, x - 1 , y + 45, z - 1);
		}
	}

	@SuppressWarnings("deprecation")
	public boolean generate(World world, Random rand, int i, int j, int k) {

		//world.getBlockAt(i + 3, j + 5, k + 3).setTypeIdAndData(35, (byte) 4, true);
		//world.getBlockAt(i + 17, j + 0, k + 6).setType(Material.GLOWSTONE);
		
		world.getBlockAt(i + 0, j + 12, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 13, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 14, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 15, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 16, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 17, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 0, j + 18, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 9, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 10, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 12, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 12, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 12, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 13, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 13, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 13, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 14, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 1, j + 14, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 14, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 14, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 15, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 15, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 15, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 16, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 16, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 16, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 17, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 17, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 17, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 18, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 18, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 1, j + 18, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 19, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 20, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 1, j + 21, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 7, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 8, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 9, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 9, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 9, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 10, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 10, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 10, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 11, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 11, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 11, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 12, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 12, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 13, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 2, j + 13, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 14, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 2, j + 14, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 15, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 2, j + 15, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 16, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 16, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 17, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 17, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 18, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 18, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 19, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 19, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 19, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 20, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 20, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 20, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 21, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 21, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 2, j + 21, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 2, j + 23, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 7, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 7, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 3, j + 7, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 8, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 8, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 3, j + 8, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 9, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 9, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 10, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 10, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 11, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 11, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 12, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 12, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 13, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 13, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 14, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 3, j + 14, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 14, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 15, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 15, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 16, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 16, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 17, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 17, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 18, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 18, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 19, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 19, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 20, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 20, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 21, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 21, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 22, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 3, j + 22, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 22, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 3, j + 22, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 23, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 23, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 3, j + 23, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 3, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 6, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 4, j + 6, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 6, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 4, j + 6, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 7, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 7, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 8, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 8, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 9, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 9, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 10, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 10, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 11, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 11, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 12, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 13, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 14, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 15, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 16, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 17, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 18, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 19, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 19, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 19, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 20, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 20, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 21, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 4, j + 21, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 21, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 22, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 4, j + 22, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 23, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 4, j + 23, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 24, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 24, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 4, j + 24, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 4, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 5, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 5, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 5, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 5, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 6, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 5, j + 6, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 6, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 7, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 5, j + 7, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 7, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 8, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 8, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 8, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 9, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 10, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 19, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 20, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 21, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 22, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 5, j + 22, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 22, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 23, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 23, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 24, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 24, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 25, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 5, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 5, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 3, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 4, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 6, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 5, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 5, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 6, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 6, j + 6, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 6, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 7, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 8, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 23, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 24, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 24, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 25, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 25, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 26, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 6, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 6, j + 27, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 2, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 3, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 7, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 4, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 4, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 26, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 7, j + 26, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 27, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 7, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 7, j + 28, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 2, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 3, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 8, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 4, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 4, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 25, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 8, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 26, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 8, j + 26, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 27, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 8, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 27, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 8, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 8, j + 28, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 2, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 9, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 26, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 9, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 9, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 9, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 2, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 10, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 10, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 10, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 2, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 11, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 11, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 11, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 12, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 2, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 3, k + 1).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 12, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 28, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 12, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 12, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 13, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 2, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 13, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 3, k + 1).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 13, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 4, k + 1).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 13, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 28, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 13, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 13, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 14, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 2, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 3, k + 1).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 14, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 28, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 14, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 14, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 14, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 15, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 2, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 27, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 15, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 28, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 15, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 29, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 15, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 15, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 15, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 16, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 2, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 28, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 16, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 16, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 16, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 17, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 2, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 17, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 28, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 17, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 17, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 0, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 1, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 18, j + 1, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 1, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 18, j + 1, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 2, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 18, j + 2, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 3, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 18, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 28, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 28, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 29, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 29, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 18, j + 29, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 18, j + 30, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 2, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 19, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 2, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 19, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 19, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 19, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 20, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 20, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 1, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 2, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 2, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 3, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 3, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 26, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 21, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 27, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 27, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 28, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 28, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 21, j + 28, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 21, j + 29, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 2, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 3, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 22, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 4, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 4, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 25, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 22, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 26, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 22, j + 26, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 27, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 22, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 27, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 22, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 22, j + 28, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 2, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 3, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 3, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 23, j + 3, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 4, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 4, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 26, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 23, j + 26, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 27, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 27, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 23, j + 27, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 23, j + 28, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 3, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 4, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 4, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 24, j + 4, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 5, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 5, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 6, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 6, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 7, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 8, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 23, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 24, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 24, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 25, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 25, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 26, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 26, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 24, j + 26, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 24, j + 27, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 4, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 5, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 5, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 25, j + 5, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 6, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 6, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 7, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 7, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 7, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 8, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 8, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 9, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 10, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 19, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 20, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 21, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 22, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 22, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 23, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 23, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 24, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 24, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 25, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 25, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 25, j + 25, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 25, j + 26, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 5, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 6, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 6, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 26, j + 6, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 7, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 7, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 8, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 8, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 9, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 9, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 10, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 26, j + 10, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 10, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 11, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 11, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 12, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 13, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 14, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 15, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 16, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 17, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 18, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 19, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 19, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 20, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 20, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 21, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 21, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 21, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 22, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 22, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 23, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 23, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 24, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 24, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 26, j + 25, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 6, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 7, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 7, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 27, j + 7, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 8, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 8, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 27, j + 8, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 9, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 27, j + 9, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 10, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 27, j + 10, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 11, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 27, j + 11, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 12, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 12, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 13, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 13, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 14, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 14, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 15, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 15, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 16, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 16, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 17, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 17, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 18, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 27, j + 18, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 18, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 18, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 19, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 19, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 20, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 20, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 21, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 21, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 22, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 22, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 27, j + 22, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 23, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 23, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 27, j + 23, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 27, j + 24, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 7, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 8, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 9, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 9, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 9, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 10, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 28, j + 10, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 10, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 10, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 11, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 11, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 11, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 12, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 12, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 13, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 13, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 14, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 14, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 15, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 15, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 16, k + 0).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 16, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 17, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 28, j + 17, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 18, k + 0).setTypeIdAndData(35,  (byte) 14, true);
		world.getBlockAt(i + 28, j + 18, k + 4).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 19, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 28, j + 19, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 19, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 19, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 20, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 20, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 20, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 21, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 21, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 28, j + 21, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 22, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 28, j + 23, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 9, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 10, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 11, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 12, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 12, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 12, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 13, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 13, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 13, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 14, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 14, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 14, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 15, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 15, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 15, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 16, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 16, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 16, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 17, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 17, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 17, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 18, k + 0).setTypeIdAndData(5,  (byte) 2, true);
		world.getBlockAt(i + 29, j + 18, k + 1).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 18, k + 2).setType(Material.GLOWSTONE);
		world.getBlockAt(i + 29, j + 18, k + 3).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 19, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 20, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 29, j + 21, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 12, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 13, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 14, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 15, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 16, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 17, k + 2).setTypeIdAndData(18,  (byte) 1, true);
		world.getBlockAt(i + 30, j + 18, k + 2).setTypeIdAndData(18,  (byte) 1, true);

		return true;
	}
}
